CPWL_Dash: switch to universal init
E.g. clang-15 in -std=c++20 mode fails without this with the following
error message:

pdfium/fpdfsdk/pwl/cpwl_wnd.cpp:43:7: error: no matching constructor for initialization of 'CPWL_Dash'
      sDash(3, 0, 0) {}
      ^     ~~~~~~~
pdfium/fpdfsdk/pwl/cpwl_wnd.h:61:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
struct CPWL_Dash {
       ^
pdfium/fpdfsdk/pwl/cpwl_wnd.h:61:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
pdfium/fpdfsdk/pwl/cpwl_wnd.h:61:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 3 were provided
1 error generated.

Switching to universal init restores the ability to build with this
compiler, as it was working in the past.

Change-Id: I48b2079b87cce9bc4e2ec7b813e21ea5bcb786d3